### ISSUE TITLE
加个联系方式

### ISSUE THREAD

**Issue by YushengWHU** [wwtinwhu/Thoughts_DuringPhd#1]
老哥我是中心的，也是做slam的，方便的话可以加个微信一起交流一下，我在lio-sam issue看见你的

**Comment by wwtinwhu** [comment]
> 老哥我是中心的，也是做slam的，方便的话可以加个微信一起交流一下，我在lio-sam issue看见你的

你好，github主页有留邮箱，期待进一步的交流。
